//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace End_Project.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_table
    {
        public int admin_id { get; set; }
        public string admin_login { get; set; }
        public string admin_password { get; set; }
    }
}
