//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace End_Project.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tech_type_table
    {
        public int tech_type_id { get; set; }
        public string tech_type_name { get; set; }
    }
}
